### ISSUE TITLE
create toolkit error

### ISSUE THREAD

**Issue by Khethani** [watson-developer-cloud/discovery-starter-kit#4]
When clicking Create Toolkit, it takes me to bluemix but when on Bluemix it doesn't allow me to create the toolkit.

**Comment by maniax89** [comment]
I am aware of the the issue and I have a work in progress coming sometime next week - I will update this issue when it is fixed. thanks for pointing it out!

**Comment by maniax89** [comment]
@Khethani could you give the button another try?

**Comment by Khethani** [comment]
I tried it and it works now. Thanks @maniax89
